---
kind: pipeline
name: default

steps:
  - name: link & unlink
    image: archlinux
    pull: always
    commands:
      - pacman -Suy --noconfirm --needed make git stow sudo vim tmux emacs
      - "echo 'root ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers"
      - make link-all
      - make unlink-all

  - name: full install
    image: oblique/archlinux-yay
    pull: always
    commands:
      - "echo 'root ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers"
      - ./bootstrap.sh --no-creds --no-lang --no-yay
      -  make YAY='sudo -u aur yay -S --noconfirm --needed' HASKELL_DEPENDENCIES=''

  - name: notify
    image: plugins/matrix
    settings:
      homeserver:
        from_secret: matrix_homeserver
      roomid:
        from_secret: matrix_roomid
      username:
        from_secret: matrix_username
      password:
        from_secret: matrix_password
    depends_on: [ "link & unlink", "full install" ]
