#!/bin/sh

case "$1" in
    enable|disable)
        ;;
    *)
        echo "Unkown command '$1'" >&2
        echo "Usage: '$0 <enable|disable>'" >&2
        exit 1
        ;;
esac

xautolock "-$1"

notify-send -u low "Toggled Xautolock (${1}d)" \
    -h string:x-canonical-private-synchronous:xautolock-toggle # Override previous one
