#! /bin/sh

# Device id according to xinput list
device=11
state=$(xinput list-props "$device" | grep "Device Enabled" | grep -o "[01]$")

if [ "$state" == "1" ];then
  xinput --disable "$device"
  notify-send -u low "Toggled touchpad (disabled)"
else
  xinput --enable "$device"
  notify-send -u low "Toggled touchpad (enabled)"
fi
